version: '3'
services:
  qb-backend:
    image: kritr/phoenix
    ports:
    - "8080:4000" 
    volumes:
    - .:/code
    links:
    - db
    command: mix serve
  db:
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
